root:
  label: "Index"

categories:
  - "Science"
  - "Systems Engineering"
  - "Software"

sections:
  - label: "Tasks needed to get to CDR"
    parent: "Index"
    categories: []
    tasks: []

  - label: "Science Tasks"
    parent: "Index"
    categories:
      - "Science"
    tasks:
      - label: "Update GNAO ConOps"

  - label: "Science + Systems Engineering Tasks"
    parent: "Index"
    categories:
      - "Science"
      - "Systems Engineering"
    tasks:
      - label: "Create GNAO OpsCon"
      - label: "Create AOS OpsCon"
      - label: "Create GFC OpsCon"

  - label: "Systems Engineering Tasks"
    parent: "Index"
    categories:
      - "Systems Engineering"
    tasks:
      - label: "Finalize MindMaps"
      - label: "Create GFC Subsystem Spec"
      - label: "Update AOSC Subsystems Spec/Reqs"
      - label: "Create AOSC Verification and Validation plan"
      - label: "Create GFC Verification and Validation plan"
      - label: "Create ICDs"

  - label: "Systems Engineering + Software Tasks"
    parent: "Index"
    categories:
      - "Systems Engineering"
      - "Software"
    tasks:
      - label: "Create AOS FID"
      - label: "Create GFC FID"
      - label: "Update Obs Seq. Interactions document"

  - label: "Software Tasks"
    parent: "Index"
    categories:
      - "Software"
    tasks:
      - label: "Create AOS FDD"
      - label: "Create GFC FDD"
      - label: "Update AOSC Arch design document"
      - label: "Create GFC Arch design document"
      - label: "Update UI document and SW ICDs"
      - label: "Update GCS and Core Arch documents"
